/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admTK;


import static admTK.pendataansiswa.tblTK;
import static admTK.pendataansiswa.tgl;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class administrasiPendaftaranSiswa extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    koneksi koneksi;

    /**
     * Creates new form Pembayaran
     */
    public administrasiPendaftaranSiswa() {
        koneksi=new koneksi();
        initComponents();
        simpan.setEnabled(false);
        ttotal.setEditable(false);
        status.setEditable(false);
        jTextArea1.setEditable(false);
        output();
        icon(); 
    }
    
     public void icon(){
    ImageIcon ico = new ImageIcon("src/Gambar/background.jpg");
    setIconImage(ico.getImage());
    }
    
    private void output(){
       Object header[] = {"No","NIS","Tanggal","Keterangan","Jumlah","Total","Status"};
        DefaultTableModel isi = new DefaultTableModel(null, header);
        tblpendaftaran.setModel(isi);
        
        String sql = "SELECT * from pendaftaran";
        try{
            st = koneksi.con.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()){
                //int k0 = rs.;
                String k1 = rs.getString(1);
                String k2 = rs.getString(2);
                String k4 = rs.getString(4);
                String k3 = rs.getDate(3).toString();
                String k5 = rs.getString(5);
                String k6 = rs.getString(6);
                String k7 = rs.getString(7);
          
                
                String kolom[] = {k1,k2,k3,k4,k5,k6,k7};
                isi.addRow(kolom);
               
            }
            st.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"error : "+e.getMessage());
        }
    }
    
    private void input(){
        String tanggal = "YYYY-MM-dd HH:mm:ss";
        String ket = null;
        Timestamp tgl = new Timestamp(new Date().getTime());
        //int id = 0;
       try { 
       
                    st = koneksi.con.createStatement();
                    String sql = "INSERT INTO pendaftaran (nis,tanggal,keterangan,jumlah,total,status) values ('"+nis.getText()+"',"
                            + "'"+new SimpleDateFormat(tanggal).format(tgl)+"',"
                            + "'"+cicilan.getSelectedItem()+"',"
                            + "'"+ttotal.getText()+"',"
                            + "'"+jmlhpendaftaran.getText()+"',"
                            + "'"+status.getText()+"')";
                          
                                  
                      JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
                    st.executeUpdate(sql);
                 
      }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
       }  
    }
    
     private void reset(){
        nis.setText("");
        cicilan.setSelectedItem("");
        jmlhpendaftaran.setText("");
        ttotal.setText("");
        status.setText("");
       
    }
     
     private void total(){
        int jmlh = Integer.parseInt(jmlhpendaftaran.getText());
        int totl = 0;
        int ttal = jmlh+totl;
        ttotal.setText(Integer.toString(ttal));
    }
    
    private void status(){
        int  to =Integer.parseInt(ttotal.getText());
        if (to==700000){
            status.setText("LUNAS");
            simpan.setEnabled(true);
        } else if (to >=700000){ 
            status.setText("Melebihi Pembayaran");
            simpan.setEnabled(false);
        } else {
            status.setText("BELUM LUNAS");
            simpan.setEnabled(true);
        }
       }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cicilan = new javax.swing.JComboBox<>();
        nis = new javax.swing.JTextField();
        jmlhpendaftaran = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtcari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        ttotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpendaftaran = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel4.setText("NIS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 138, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel7.setText("Jumlah");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel10.setText("Pembayaran");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        cicilan.setFont(new java.awt.Font("Tekton Pro", 1, 14)); // NOI18N
        cicilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cicilan 1", "cicilan 2" }));
        getContentPane().add(cicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, 31));
        getContentPane().add(nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 127, 230, 30));

        jmlhpendaftaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmlhpendaftaranKeyPressed(evt);
            }
        });
        getContentPane().add(jmlhpendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 230, 34));

        jTextArea1.setBackground(new java.awt.Color(102, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Notes!\n\nTotal Pembayaran Uang Gedung\nTK Islam Ruhama Bekasi\nRp.700,000,-");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 249, 160));
        getContentPane().add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 230, 31));

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 34));

        simpan.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon-55391.png"))); // NOI18N
        simpan.setText("save");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 120, 51));
        getContentPane().add(ttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 230, 35));

        jLabel3.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel3.setText("Total");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 230, 32));

        jLabel5.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel5.setText("Status");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("*Enter");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jLabel13.setText("Untuk memperoleh Total dan Status");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logotkkecilLL.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel1.setText("Administrasi Pendaftaran Siswa");

        jLabel2.setFont(new java.awt.Font("NSimSun", 1, 24)); // NOI18N
        jLabel2.setText("TK Islam Ruhama Bekasi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(491, 491, 491)
                .addComponent(jLabel8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-290, 0, 1190, 120));

        tblpendaftaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpendaftaranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpendaftaran);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 665, 110));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home (2).jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 72, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 120, 580, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel9.setText("\n");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        input();
        output();
        reset();
    }//GEN-LAST:event_simpanActionPerformed

    private void tblpendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpendaftaranMouseClicked
        // TODO add your handling code here:
        String PS = String.valueOf(administrasiPendaftaranSiswa.tblpendaftaran.getValueAt(administrasiPendaftaranSiswa.tblpendaftaran.getSelectedRow(),0));
        System.out.println(PS);
        String sql = "SELECT * FROM pendaftaran WHERE id_pembayaran ='"+PS+"'";
        try{
            st = koneksi.con.createStatement();
            rs = st.executeQuery(sql);
            rs.next();
            nis.setText(rs.getString(1));
            cicilan.setSelectedItem(rs.getString(2));
            tgl.setDate (rs.getDate(3));
            jmlhpendaftaran.setText(rs.getString(4));
            ttotal.setText(rs.getString(5));
            status.setText(rs.getString(6));
            
            }catch (Exception e){
            JOptionPane.showMessageDialog(null,"error : "+e.getMessage());
        }
    }//GEN-LAST:event_tblpendaftaranMouseClicked

    private void jmlhpendaftaranKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmlhpendaftaranKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            total();
            status ();
        }
    }//GEN-LAST:event_jmlhpendaftaranKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new menuutama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrasiPendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrasiPendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrasiPendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrasiPendaftaranSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrasiPendaftaranSiswa().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cicilan;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jmlhpendaftaran;
    private javax.swing.JTextField nis;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField status;
    public static javax.swing.JTable tblpendaftaran;
    private javax.swing.JTextField ttotal;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
