
package admTK;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class menuutama extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    koneksi koneksi;

    /**
     * Creates new form menuutama
     */
    public menuutama() {
        koneksi=new koneksi();
        initComponents();
    }
    private void koneksi(){
        Connection con;
        String id, pass, driver, url;
        id= "root";
        pass = " ";
        driver = "com.mysql.jdbc.Driver";
        url = "jdbc:mysql://localhost/administrasi";
        try{
            Class.forName(driver).newInstance();
            con = DriverManager.getConnection(url,id,pass);
            if (con==null){
                JOptionPane.showMessageDialog (null,"KONEKSI DATABASE GAGAL");
            }
        } catch (Exception e){
            System.out.println(""+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Menudatamurid = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        pendaftaransiswa = new javax.swing.JMenuItem();
        spp = new javax.swing.JMenuItem();
        alatseragam = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        laporanadm = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/MENU2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(jLabel2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/bukuudata.png"))); // NOI18N
        jMenu1.setText("Pendataan Siswa");
        jMenu1.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N

        Menudatamurid.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 12)); // NOI18N
        Menudatamurid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/google-docs.png"))); // NOI18N
        Menudatamurid.setText("Pendataan siswa");
        Menudatamurid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenudatamuridActionPerformed(evt);
            }
        });
        jMenu1.add(Menudatamurid);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/uang.jpg"))); // NOI18N
        jMenu4.setText("Administrasi");
        jMenu4.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N

        pendaftaransiswa.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        pendaftaransiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/buku.jpg"))); // NOI18N
        pendaftaransiswa.setText("Pendaftaran Siswa");
        pendaftaransiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendaftaransiswaActionPerformed(evt);
            }
        });
        jMenu4.add(pendaftaransiswa);

        spp.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        spp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/spp.jpg"))); // NOI18N
        spp.setText("SPP");
        spp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sppActionPerformed(evt);
            }
        });
        jMenu4.add(spp);

        alatseragam.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        alatseragam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/alat dan seragam1.jpg"))); // NOI18N
        alatseragam.setText("Alat dan seragam");
        alatseragam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alatseragamActionPerformed(evt);
            }
        });
        jMenu4.add(alatseragam);

        jMenuBar1.add(jMenu4);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/inscripcion.png"))); // NOI18N
        jMenu2.setText("Laporan");
        jMenu2.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N

        laporanadm.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        laporanadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/inscripcion.png"))); // NOI18N
        laporanadm.setText("Laporan");
        laporanadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanadmActionPerformed(evt);
            }
        });
        jMenu2.add(laporanadm);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/remove.png"))); // NOI18N
        jMenu3.setText("Exit");
        jMenu3.setFont(new java.awt.Font("Lithos Pro Regular", 0, 12)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar icon/remove.png"))); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laporanadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanadmActionPerformed
        // TODO add your handling code here:
         new cetakadm().setVisible(true);
        dispose();
    }//GEN-LAST:event_laporanadmActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void alatseragamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alatseragamActionPerformed
        // TODO add your handling code here:
         new alatdanseragam().setVisible(true);
        dispose();
    }//GEN-LAST:event_alatseragamActionPerformed

    private void sppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sppActionPerformed
        // TODO add your handling code here:
         new pembayaranSPP().setVisible(true);
        dispose();
    }//GEN-LAST:event_sppActionPerformed

    private void MenudatamuridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenudatamuridActionPerformed
        // TODO add your handling code here:
        new pendataansiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_MenudatamuridActionPerformed

    private void pendaftaransiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendaftaransiswaActionPerformed
        // TODO add your handling code here:
        new administrasiPendaftaranSiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_pendaftaransiswaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menudatamurid;
    private javax.swing.JMenuItem alatseragam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem laporanadm;
    private javax.swing.JMenuItem pendaftaransiswa;
    private javax.swing.JMenuItem spp;
    // End of variables declaration//GEN-END:variables
}
